### ISSUE TITLE
 ER_NOT_SUPPORTED_AUTH_MODE: Mysql 8.0

### ISSUE THREAD

**Issue by Julien-R44** [Julien-R44/adonis-sail#1]
When MySQL 8 is used this error is encountered: 
```
ER_NOT_SUPPORTED_AUTH_MODE: 
  Client does not support authentication protocol requested by server; consider upgrading MySQL client 
```
## Workaround 
Replace mysql image in docker-compose.yml :
```
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
```
with this :
```
  mysql:
    image: 'mysql/mysql-server:5.7'
    container_name: mysql
```

See : https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

**Comment by CaiqueLaurentino** [comment]
Another option to not need to change the password is to use mysql2.

**Comment by ruanitto** [comment]
> Another option to not need to change the password is to use mysql2.

yarn add mysql2 on adonisjs project, and change client on config/database.ts to mysql2

**Comment by Julien-R44** [comment]
As simple as that! Thanks guys, I didn't have much time to read up on it. I will add a note in the README about this. Thanks!
