### ISSUE TITLE
aide docker

### ISSUE THREAD

**Issue by j314h** [Julien-R44/adonis-sail#5]
Bonjour, je suis vraiment désoler d'écrire ici , je ne sait pas du tous comment vous contactez, sans vous déranger. 

Donc je vous contact car j'aime adonis mais là j'ai les yeux qui pleure ^^ 
j'essaie tant bien que mal de dockerizer mon projet adonis, je suis la doc partie dockerization
tous ce passe bien mon docker compose s'execute etc ... mais quand j'ouvre le navigateur
là aussi la partie serveur du site fonctionne mais le webpack encore fait défaut et n'arrive pas à rendre les fichiers.
(j'ai bien suivis la partie de la doc qui modifie le docker-compose pour webpack encore) donc de ce coté là
je suis sur que tout est ok.

j'ai tester beaucoup de chose sans réponse positive.
j'ai trouver un contournement et mais cela me fait perdre mes cheveux
=> 
dans public/entrypoints.json je modifie à la main le host, je passe 0.0.0.0 à localhost et sa fonctionne
bien sur si j'arrête le contenu faut que je recommence, donc c'est clairement pas une bonne solution (même de contournement ^^)
j'ai donc par la suite essayer de modifier mon host au lieu de 0.0.0.0 => localhost cela ne règle pas le soucis
je dois le faire manuellement pour que sa fonctionne (c'est là que je pleure), je vous demande de l'aide car j'aimerais 
dockerizer pour la prod. (donc je test) 

si vous avez une solution je suis preneur, je vous dérange, passer mon message à la poubelle je ne veux vraiment pas vous faire perdre votre temps, encore une fois désoler d'écrire ici, j'ai demandé sur discord mais je n'ai pas réussis à trouvé une solution
merci de m'avoir lu à bientôt j'espère 
![Capture d’écran 2022-06-07 145417](https://user-images.githubusercontent.com/61687824/172384742-9a2415da-f1d0-464d-b2fd-1f7e1c504290.png)
![Capture d’écran 2022-06-07 145632](https://user-images.githubusercontent.com/61687824/172385151-7f888585-af34-4b00-b824-86e8d6aed77d.png)

**Comment by Julien-R44** [comment]
Hello, désolé je pourrais pas t'aider, je n'utilise pas docker en production pour mes applications Adonis et cela ne semble pas avoir de rapport avec Adonis Sail. 
Je te conseille plutôt de poster un thread sur le Github Discussions d'Adonis, tu auras sûrement des réponses
